### ISSUE TITLE
Feature request: autoplay gifs when swiping to them? 

### ISSUE THREAD

**Issue by Pentaphon** [anegrin/chiver#12]
The experience would be a lot faster and more enjoyable if gifs opened without having to press the play button each time. Could we get such a feature? I suppose you could add a simple 3 button menu to toggle autoplay on and off if you want it to be configurable. 

Thanks in advance.

**Comment by anegrin** [comment]
https://github.com/anegrin/chiver/releases/tag/2.1.0
